import {
  CLIMATE_ASSESSMENT_PEAK_WARMING_MEDIAN,
  CLIMATE_ASSESSMENT_WARMING_2100_MEDIAN,
  EMISSIONS_DIAGNOSTICS_CUMULATIVE_CCS_2020_2100_Gt_CO2,
  EMISSIONS_DIAGNOSTICS_CUMULATIVE_CO2_2020_2100_Gt_CO2,
} from "@/lib/config/filters/advanced-filters-config";
import { IS_PART_OF_SCI_2025, VETTING2025 } from "@/lib/config/reasons-of-concern/category-config";
import { LAND_FOREST_COVER } from "@/lib/config/filters/land-filter-config";
import {
  CLIMATE_CATEGORY_META_INDICATOR_KEY,
  CUMULATIVE_CCS_META_INDICATOR_KEY,
  CUMULATIVE_CO2_EMISSIONS_META_INDICATOR_KEY,
  YEAR_NET_ZERO_CO2_META_INDICATOR_KEY,
  YEAR_NET_ZERO_GHG_META_INDICATOR_KEY,
  PEAK_TEMPERATURE_META_INDICATOR_KEY,
  YEAR_PEAK_TEMPERATURE_META_INDICATOR_KEY,
  CUMULATIVE_CO2_NET_NEGATIVE_EMISSIONS_META_INDICATOR_KEY,
} from "@/lib/config/filters/climate-filter-config";
import { SCENARIO_TYPOLOGY_META_KEY } from "@/lib/config/filters/typology-filter-config";

export const ENSEMBLE_WEIGHT_SCI_2025_BETA = "Ensemble Weight|SCI 2025 [beta]";

export const REQUIRED_META_KEYS = [
  EMISSIONS_DIAGNOSTICS_CUMULATIVE_CCS_2020_2100_Gt_CO2,
  EMISSIONS_DIAGNOSTICS_CUMULATIVE_CO2_2020_2100_Gt_CO2,
  CLIMATE_ASSESSMENT_PEAK_WARMING_MEDIAN,
  CLIMATE_ASSESSMENT_WARMING_2100_MEDIAN,
  ENSEMBLE_WEIGHT_SCI_2025_BETA,
  VETTING2025,
  IS_PART_OF_SCI_2025,
  LAND_FOREST_COVER,
  CLIMATE_CATEGORY_META_INDICATOR_KEY,
  YEAR_NET_ZERO_CO2_META_INDICATOR_KEY,
  YEAR_NET_ZERO_GHG_META_INDICATOR_KEY,
  CUMULATIVE_CO2_EMISSIONS_META_INDICATOR_KEY,
  CUMULATIVE_CO2_NET_NEGATIVE_EMISSIONS_META_INDICATOR_KEY,
  CUMULATIVE_CCS_META_INDICATOR_KEY,
  PEAK_TEMPERATURE_META_INDICATOR_KEY,
  YEAR_PEAK_TEMPERATURE_META_INDICATOR_KEY,
  SCENARIO_TYPOLOGY_META_KEY,
];
